name: FFA
version: 3.0
api-version: 1.16
main: com.gmail.mariodeu2.ffa.Main
depend: [
    AuthMe,
    CommandApi
]
commands:
  ffa:
    description: FFA command
    usage: /ffa
    permission: ffa.Main
    aliases: [freeforall]
  stats:
    description: Stats command
    usage: /stats
    permission: ffa.stats
    aliases: [kills, deaths, killstreak]
  points:
    description: Points command
    usage: /points
    permission: ffa.points